### ISSUE TITLE
Word Bank issues

### ISSUE THREAD

**Issue by hendrikafrilian** [smintf/duohacker#5]
its not workng on the word bank challenge. how to fix this? im on a Japanese language learning

**Comment by smintf** [comment]
Hmm i'll check it out, mind sending me the exact skill & level that is causing said problem?
In the meantime, try out [Autolingo](https://github.com/smintf/autolingo/), as its more regularly maintained.

**Comment by hendrikafrilian** [comment]
![image](https://user-images.githubusercontent.com/99241108/161662564-851524fb-76f4-4879-8e05-1817c0aba59d.png)
Thankyou for replying. its not working when it comes to a challenge like that, and that's happened on every stage. Yeah i'm using autolingo rn. thank you for recommending

**Comment by smintf** [comment]
Aight, i'll check it out.
