### ISSUE TITLE
This script doesn't work on some questions, will it be fix any time soon?

### ISSUE THREAD

**Issue by EKHH** [smintf/duohacker#6]
I understand that Autolingo may be a lot better alternative, but I found this script a lot more helpful since it’s doesn’t require download and installration (which, in my case, isn’t possible) and universally available, allowing access on any device (Working on iOS, with slower interval). But it doesn’t seem to work on some questions (match) and doesn’t support stories mode (Some questions in stories mode can be solved simply with this XD: `setInterval(function(){for(var t=document.getElementsByClassName("_2igzU _1xWrt _3LUrt _2P5W7"),e=0;e<t.length;e++)t[e].style.color,t[e].style.color="#4B4B4B"},20);`). I’m not good enough to fix it… But will it be fix any time soon?

**Comment by smintf** [comment]
use [autolingo](https://github.com/smintf/autolingo/) in the meantime.

**Comment by smintf** [comment]
> I understand that Autolingo may be a lot better alternative, but I found this script a lot more helpful since it’s doesn’t require download and installration (which, in my case, isn’t possible) and universally available, allowing access on any device (Working on iOS, with slower interval). But it doesn’t seem to work on some questions (match) and doesn’t support stories mode (Some questions in stories mode can be solved simply with this XD: `setInterval(function(){for(var t=document.getElementsByClassName("_2igzU _1xWrt _3LUrt _2P5W7"),e=0;e<t.length;e++)t[e].style.color,t[e].style.color="#4B4B4B"},20);`). I’m not good enough to fix it… But will it be fix any time soon?

Unless I figure out a way to change the size of a window using javascript, not anything soon.

**Comment by EKHH** [comment]
> > I understand that Autolingo may be a lot better alternative, but I found this script a lot more helpful since it’s doesn’t require download and installration (which, in my case, isn’t possible) and universally available, allowing access on any device (Working on iOS, with slower interval). But it doesn’t seem to work on some questions (match) and doesn’t support stories mode (Some questions in stories mode can be solved simply with this XD: `setInterval(function(){for(var t=document.getElementsByClassName("_2igzU _1xWrt _3LUrt _2P5W7"),e=0;e<t.length;e++)t[e].style.color,t[e].style.color="#4B4B4B"},20);`). I’m not good enough to fix it… But will it be fix any time soon?
> 
> Unless I figure out a way to change the size of a window using javascript, not anything soon.

Won't iframe work?
